version: '3.7'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    ports: 
      - "9000:6379"

