name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v1.2.1
      env:
        cache-name: cache-node-modules
      with:
        path: cd caches
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
        cache-dependency-path: subdir/go.sum
        
    - name: Build Backend
      run: cd backend && go build
    - name: Build Frontend
      run: cd frontend && go build
  
  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
        cache-dependency-path: subdir/go.sum
        

    - name: Test Frontend
      run: cd frontend && go test
    
